- hosts: all
  tasks:
    - name: Build and install librdkafka 1.4.0+
      block:
        - name: Install librdkafka build dependencies
          apt:
            name:
              - liblz4-dev
              - libsasl2-dev
              - libssl-dev
              - libzstd-dev
              - python3
              - zlib1g-dev
              - debhelper
              - devscripts
              - wget
              - build-essential
            state: present
            install_recommends: no
          become: true

        - name: Create build directory
          tempfile:
            state: directory
          register: build_dir

        - name: Fetch librdkafka from Debian 'testing'
          command: "dget -u https://snapshot.debian.org/archive/debian/20200513T084344Z/pool/main/libr/librdkafka/librdkafka_1.4.2-1.dsc"
          args:
            chdir: "{{ build_dir.path }}"

          # NOTE(hrw): use '-d' to skip 'error: Unmet build dependencies: debhelper-compat (= 13)'
        - name: Build librdkafka package
          shell:
            cmd: |
              set +o errexit
              set -o xtrace

              debuild -b -d
              ls -l ../*
              sudo debi
            executable: /bin/bash
            chdir: "{{ build_dir.path }}/librdkafka-1.4.2/"
